[project]
name = "dad-jokes"
version = "0.1.0"
description = ""
authors = [
    {name = "Donald Elger",email = "delger@uidaho.edu"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2,<6.0",
    "whitenoise>=6.9,<7.0",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
